version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./local_data:/data
    environment:
      - DATABASE_URL=file:/app/data/gemini-balance.db
      # Add other necessary environment variables here
